import { Manrope } from "next/font/google";
import "./globals.css";
import { twMerge } from "tailwind-merge";
import NavBar from "@/components/NavBar";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={twMerge(manrope.className, 'p-[18px]')}>
        <NavBar />
        {children}
        </body>
    </html>
  );
}
